const message = {
    NAME: "Please Enter Name",
    DELETE_PROFILE: "Delete successful!! ",
    DELETE_PROFILE_FAILD: "User Not Found!! ",
    EMAIL: "Please Enter Correct Email",
    GENDER: "Please Provide Gender",
    PHONE: "Please Enter Mobile Number",
    ERROR_MESSAGE: "ERROR!! ",
    PROFILE: "Your Profile !! ",
    PROFILE_ERROR: "Invalid Email and Password!! ",
    LOGIN_ERROR: "Invalid Email and Password !! ",
    PASSWORD: "Password Incorrect",
    PASSWORD_RESET: "Password Changed Successfully!! ",
    PASSWORD_RESET_FAILD: "Password Doesn't Changed Please Retry !!",
    PASSWORD_CONFIRM_FAILD: "Your Confirm Password Incorrect!!",
    ABOUT_DATA: "Data Saved Successfully!!",
    USER_EXITS: "User Already Exists!!",
    USER_NOT_EXITS: "User Not Exists!!",
    STATUS_SUCCESS: "Success !!",
    STATUS_FAILED: "Failed !!",
    LOGIN_SUCCESS: "Login Successfully !!",
    USER_UPDATE: "User Update Successfully !!",
    AUTH_ERROR: "Auth-Error!!",
    INVALID_TOKEN: "Invalid Token",
    STATUS_BLOG_SUCCESS: "Blog Added Successfully!!!!!!!!!!",
    DELETE_AUTHOR_FAILD: "Author Deletion Faild",
    DELETE_AUTHOR_SUCCESS: "Author Deletion Successfully!!!!!!!!",
    GETUSER_BLOG: "Your blog!!!!!!!!!!!!!!!!!!!!",
    ADD_BLOG_CATCH: "Could not add Blog please check your try block",
    BLOG_UPDATE: "Blog Update Successfully!!!!1",
    BLOG_ID_INCOORECT: "Blog ID Incorrect",
    COMMENT_STATUS_SUCCESS: "Comment successfully!!!!!!",
    VIEW_ALL_COMMENT: "Your all Comments!!!!!!",
    ADMIN_ERROR: "Your are not able to Register as Admin please login with User id !!",
    USER_FAILD: "You are not Authorised as Admin!! ",
    MY_PROFILE: "My profile!!!!!!!!!!!",
    DELETE_PROFILE_DELETE: "Profile Image Remove Successfully !!!!!!!!",
    VIEW_ALL_BLOG: "View All Blogs!!!!!!!!!!",
    VIEW_ALL_BLOG_CATCH: " Could not view all blog please check try block!!",
    VIEW_USER_BLOG: "Your Blogs!!!!!!!!",
    VIEW_USER_BLOG_CATCH: " Could not view user blog please check try block!!",
    UPDATEBLOG_CATCH: "Could not update Blog please check your try block!!",
    UPDATEBLOG_SUCCESS: "Update Blog Successfully!!!!!!!!!!!!!",
    DELETE_BLOG_SUCCESS: " Blog Delete Successfully!!!!!!!!",
    DELETE_BLOG_CATCH: "Could not delete Blog Please check your try Block!! ",
    BLOG_ID_NOT_FOUND: "Blog Id not Found!!",
    STATUS_USER_SUCCESS: "Registration Successfully !!!!!!!!!!!!!!!!!!",
    REGISTRATION_ERROR_MESSAGE: "Registration Faild please check try block!!",
    LOGIN_ERROR_MESSAGE: "Could not login please check try block!!",
    VIEW_PROFILE_ERROR_MESSAGE: "Could not view your profile please check try block!!",
    UPDATE_PROFILE_ERROR_MESSAGE: "Could not update your profile please check try block!!",
    DELETE_PROFILE_ERROR_MESSAGE: "Could not delete profile please check try block!!",
    DELETE_IMAGE_ERROR_MESSAGE: "Could not delete image please check try block!!",
    DO_NOT_COMMENT: "Your not comment on your own blog!!",
    STATUS_COMMENT_SUCCESS: "You did Comment Successfully !!!!!!!!!!!!!!!!!",
    ADD_COMMENT_FAILD: "Blog Id not found please check try block!!",
    VIEW_ALL_COMMENT_CATCH: "Could not see all comment please check try block!!",
    VIEW_BLOG_COMMENT_CATCH: "Could not see blog comment please check try block!!",
    VIEW_BLOG_COMMENT: "View your Blog Comments!!",
    UPDATE_COMMENT_CATCH: "Could not update comment please check try block!!",
    UPDATE_COMMENT: "Update Comment Successfully!!!!!!!!!!!!!!!!!",
    ADMIN_NOT_EXITS: "Admin not exists!!!!!!!!!!!!!!!!",
    PASSWORD_EMAIL_ERROR: "Please check email and password!!",
    COMMENT_UPDATE_ERROR: "Comment can not update!!",
    DELETE_ALL_COMMENT_SUCCESS: "Delete All comments Successfully!!!!!!!!!!!!!!!!!!!",
    DELETE_COMMENT_CATCH: "Could not delete comment please check try block!!",
    DELETE_ALL_COMMENT_CATCH: "Could not delete comment please check try block!!",
    DELETE_COMMENT_SUCCESS: "Delete comment successfully!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
    UPDATE_USER_ADMIN_ERROR: "Admin does not update status!!",
    USER_STATUS_FAILD: "User status failed please contact admin!!",
    NO_USER_BLOG: "No Blogs !!!!!!",
    USER_NOT_EXITS_LOGIN: "User not exists please provide correct email and check status of User!! ",
    BLOG_UPDATE_FAILD: "Blog not found",
    DELETE_COMMENT_FAILD: "You can not delete other's comments!!",
    UPDATE_COMMENT_FAILD: "You can not update other's comments!!",
    DELETE_ALL_COMMENT_FAILD: "Delete All comments faild!!",
    DELETE_ALL_COMMENT_INCORRECT: "Id is null please provide correct Id",
    LIKES_DISLIKES_ERR: "Could not likes and dislikes",
    LIKES_DISLIKES_ERROR: "Could not likes and dislikes please check try block",
    LIKES_DISLIKES_SUCCESS: "Sucessfully!!!!!!!!!!!!!!!!!!!",
    LIKES_DISLIKES_FAILD: "You can not like and dislike your own post",
    LIKES_DISLIKES_NOT_AT_TIME: "You can not likes and dislikes at time",
}



//module exports
module.exports = message